# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9f61a61cd79faa0be1d1d750ad9a7d8e11b0ff0d4aa433d2fc7b98c38574d5bd15de667b1f4b1adef8a7f98191547de52c72bec6399c845b91829e1b905500

test:
  secret_key_base: 306b468385bd1781575f3ec4bb87db5ed3dfb93c01d34272d0081d9a23efde6d844734d2c13be448dc0513fb360b58329cf245ff747e1f7347b2520dd7ad2598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
